[jenkins_agents]
agent-01 ansible_host=agent-01 ansible_connection=docker
agent-02 ansible_host=agent-02 ansible_connection=docker
agent-03 ansible_host=agent-03 ansible_connection=docker
agent-04 ansible_host=agent-04 ansible_connection=docker
agent-05 ansible_host=agent-05 ansible_connection=docker

[jenkins_agents:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
